### PR TITLE
Add TCNN model

### PR DESCRIPTION
**Pull request by ShihengDuan**
This is a definition file for the temporal convolutional model.

### CODE REVIEW

**Comment by kratzert** [comment]
Hi @ShihengDuan 

Thanks for opening this PR to add TCNN to the library. However, there is a couple of things to do before we can merge this model. 

1) The model is not designed to work with the neuralhydrology library, but uses the structure of old code from us. There is a couple of subtle differences like import names, expected inputs, etc.. A good start is to look at the TemplateModel class https://github.com/neuralhydrology/neuralhydrology/blob/ffbc60043dec4e1cfc1634cd70917291c1ee77be/neuralhydrology/modelzoo/template.py#L9 and copy your code into this structure.

Maybe have a look at the CudaLSTM model for a reference, how such a model class has to look like. Also note, that the input config is not a dictionary anymore, but an object of the `Config` class, so you will be required to add some properties to this class for addtional arguments that your model needs.

2) We would require you to add doc strings (for the format, see template.py or other models) as well as type annotations.

3) You need to link your model to the `get_model` function in https://github.com/neuralhydrology/neuralhydrology/blob/ffbc60043dec4e1cfc1634cd70917291c1ee77be/neuralhydrology/modelzoo/__init__.py#L19

4) We will need to add some files to the docs, so that your model is linked in the documentation. But we can do this later together. First, lets look that we get the model up to date.

5) In the best case scenario, it would also be good to add some tests to our test suite, but we can also discuss this later.

Let me know if you are interested in doing all this stuff or if you are overwhelmed by these requirements. In the latter case, I can also have a look at converting your code. However, this will require some time, because I am quite busy at the moment.

**Comment by ShihengDuan** [comment]
Hi @kratzert 

Thanks for the comments. I didn't realize the library has updated a lot compared with your previous one. Sorry about that. 
I have updated the model file and the `get_model` function. 
I have tested it with your previous setup but haven't done with this new library. But we can view the code first to see if it fits the new requirement. 

Thanks.

**Comment by kratzert** [comment]
Hi @ShihengDuan,

sorry for my delayed answers. I am currently in the process of finishing my thesis and don't have much time to do anything else.
Before I start a more sorrow code review, could you make sure to add docstrings to your classes and functions (for examples, look at our other models). We also use type annotations everywhere, so that would be great to add as well.

Although note, that the `cfg` input is not a dictionary anymore, but an object of the `Config` class:

https://github.com/neuralhydrology/neuralhydrology/blob/ffbc60043dec4e1cfc1634cd70917291c1ee77be/neuralhydrology/utils/config.py#L10

So all new key-words that you need in your model have to be added as class properties in the `Config` class and are then accessible via `cfg.property_name`. Again, use our other models to see how this class works and check the `Config` class to see how to add properties.
On that note, we want to try to add as little new property names as possible, so it would be good if you can re-use existing property names in your model. But this is not the most important thing right now. 

Again, sorry for my delayed answer but already as a warning, I will be quite busy the next days/weeks.

**Comment by kratzert** [comment]
Closed due to inactivity. Feel free to reopen, if you are still interested to add this model into the official library

**Pull request closed without merging**
